Args = --initialize-at-build-time=org.slf4j.LoggerFactory,ch.qos.logback \
       --initialize-at-run-time=org.springframework.cloud.bootstrap.RefreshBootstrapRegistryInitializer \
       --initialize-at-run-time=org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration
