global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gateway-service'

  - job_name: 'ticket-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ticket-service:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'ticket-service'

  - job_name: 'seat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['seat-service:8082']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'seat-service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8083']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'order-service'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8084']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'user-service'

  - job_name: 'admin-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['admin-service:8085']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'admin-service'
